import json
from pathlib import Path

ROOT = Path(__file__).parents[1]
NAMES = ["01_CALL_START_ENRICHMENT","02_CALL_END_PROCESSING","03_RECORDING_AVAILABLE","04_CALLBACK_DUE","05_CALLBACK_OVERDUE_ESCALATION","06_DNC_CONSENT_UPDATE","07_TRANSFER_REQUEST_NOTIFICATION","08_TRANSFER_FAILED_RECOVERY","09_AI_RECOMMENDATION_CREATED","10_AI_RECOMMENDATION_FEEDBACK","11_QA_SCORE_ALERT","12_COMPLIANCE_DISCLOSURE_ALERT","13_AGENT_SLA_ALERT","14_DAILY_MANAGER_REPORT","15_SYNC_FAILURE_RETRY","16_DEAD_LETTER_ALERT","17_RECONCILIATION_REPORT","18_SYSTEM_HEALTH_ALERT"]
def make(name):
    return {"name":name,"active":False,"settings":{"executionOrder":"v1"},"nodes":[{"id":"manual","name":"Test Event Input","type":"n8n-nodes-base.manualTrigger","typeVersion":1,"position":[0,0],"parameters":{}},{"id":"validate","name":"Validate Envelope","type":"n8n-nodes-base.code","typeVersion":2,"position":[220,0],"parameters":{"jsCode":"const e=$json;if(!e.event_id||!e.correlation_id||!e.schema_version||!e.occurred_at||!e.source||!e.idempotency_key||!e.event_type)throw new Error('invalid event envelope');return[{json:e}];"}},{"id":"policy","name":"Middleware Policy","type":"n8n-nodes-base.httpRequest","typeVersion":4,"position":[440,0],"parameters":{"method":"POST","url":"={{$env.MIDDLEWARE_INTERNAL_URL}}/api/v1/automation/policy-check","sendBody":True,"jsonBody":"={{$json}}","options":{"timeout":10000}}},{"id":"dead","name":"Failure to Dead Letter","type":"n8n-nodes-base.httpRequest","typeVersion":4,"position":[440,220],"parameters":{"method":"POST","url":"={{$env.MIDDLEWARE_INTERNAL_URL}}/api/v1/automation/dead-letter","sendBody":True,"jsonBody":"={{$json}}","options":{"timeout":10000}}}],"connections":{"Test Event Input":{"main":[[{"node":"Validate Envelope","type":"main","index":0}]]},"Validate Envelope":{"main":[[{"node":"Middleware Policy","type":"main","index":0}],[{"node":"Failure to Dead Letter","type":"main","index":0}]]},"Middleware Policy":{"main":[[],[{"node":"Failure to Dead Letter","type":"main","index":0}]]}},"meta":{"contract":"codestra.contact-center.v1","test_mode_only":True,"bounded_retries":3,"uses_event_id":True,"uses_correlation_id":True,"middleware_idempotency":True,"no_credentials":True,"direct_database_access":False,"direct_telephony_access":False}}
(ROOT/"workflows").mkdir(exist_ok=True)
for name in NAMES:(ROOT/"workflows"/(name+".json")).write_text(json.dumps(make(name),indent=2)+"\n")
