#!/usr/bin/env python3
"""Inventory reconciled catalog designs and declared/built n8n workflow packs."""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

try:
    from .catalog_reconciliation import (
        PACKS_DIR,
        ROOT,
        WORKFLOWS_DIR,
        catalog_reconciliation_snapshot,
        load_json,
        product_rows,
        registry_document,
        workflow_directory_for_id,
        workflow_domain_rows,
    )
except ImportError:
    from catalog_reconciliation import (  # type: ignore
        PACKS_DIR,
        ROOT,
        WORKFLOWS_DIR,
        catalog_reconciliation_snapshot,
        load_json,
        product_rows,
        registry_document,
        workflow_directory_for_id,
        workflow_domain_rows,
    )


@dataclass(frozen=True)
class WorkflowDeclaration:
    source: str
    system: str
    workflow_id: str
    expected_path: Path

    @property
    def built(self) -> bool:
        return self.expected_path.is_file()

    @property
    def relative_path(self) -> str:
        return self.expected_path.relative_to(ROOT).as_posix()


def system_from_workflow_id(workflow_id: str) -> str:
    return workflow_directory_for_id(workflow_id).name


def expected_workflow_path(workflow_id: str) -> Path:
    return workflow_directory_for_id(workflow_id) / f"{workflow_id}.json"


def pack_declarations() -> list[WorkflowDeclaration]:
    declarations: list[WorkflowDeclaration] = []
    for pack_path in sorted(PACKS_DIR.glob("*.json")):
        pack = load_json(pack_path)
        for workflow_id in pack.get("workflows", []):
            if not isinstance(workflow_id, str):
                continue
            expected_path = expected_workflow_path(workflow_id)
            declarations.append(
                WorkflowDeclaration(
                    source=pack_path.relative_to(ROOT).as_posix(),
                    system=expected_path.parent.name,
                    workflow_id=workflow_id,
                    expected_path=expected_path,
                )
            )
    return declarations


def catalog_schema_rows() -> list[dict[str, Any]]:
    return list(catalog_reconciliation_snapshot()["catalog_rows"])


def executable_workflow_files() -> list[Path]:
    return sorted(
        path
        for path in WORKFLOWS_DIR.rglob("*.json")
        if "_templates" not in path.parts
    )


def _codes(values: list[str]) -> str:
    return ", ".join(f"`{value}`" for value in values)


def inventory_markdown() -> str:
    declarations = pack_declarations()
    snapshot = catalog_reconciliation_snapshot()
    registry = registry_document()
    built = sum(item.built for item in declarations)
    lines = [
        "# Workflow Inventory",
        "",
        "Generated by `scripts/workflow_inventory.py` from the catalog registry and workflow-pack declarations.",
        "",
        "## Authoritative count model",
        "",
        f"- Registered products: {snapshot['registered_products']}",
        f"- Registered workflow domains: {snapshot['registered_workflow_domains']}",
        f"- Registered catalog files: {snapshot['registered_catalogs']}",
        f"- Raw rows across registered catalogs: {snapshot['raw_catalog_entries']}",
        f"- Canonical catalog designs: {snapshot['canonical_designs']}",
        f"- Supplemental unique designs: {snapshot['supplemental_unique_designs']}",
        f"- Compatibility-view rows: {snapshot['compatibility_view_entries']}",
        f"- **Deduplicated intended workflow designs: {snapshot['deduplicated_intended_designs']}**",
        f"- Pack workflows declared: {len(declarations)}",
        f"- Pack workflows built: {built}",
        f"- Active workflows: {snapshot['active_workflows']}",
        "- External effects enabled: false",
        "- Production changed: false",
        "",
        "> Catalog rows are not additive. The deduplicated design count is canonical IDs plus unique supplemental IDs. Compatibility views add zero. Pack declarations are a separate implementation backlog and are never added to the design count.",
        "",
        "## Catalog reconciliation",
        "",
        "| Catalog | Role | Rows | Canonical overlap | Aliases | Unique contribution |",
        "|---|---|---:|---:|---:|---:|",
    ]
    for row in snapshot["catalog_rows"]:
        lines.append(
            f"| `{row['path']}` | `{row['role']}` | {row['workflow_count']} | "
            f"{row['exact_canonical_overlap']} | {row['alias_count']} | {row['unique_contribution']} |"
        )

    lines.extend(["", "### Compatibility aliases", "", "| Legacy ID | Canonical ID |", "|---|---|"])
    for row in snapshot["alias_rows"]:
        lines.append(f"| `{row['source']}` | `{row['target']}` |")

    product_ids = [row["id"] for row in product_rows()]
    lines.extend(
        [
            "",
            "## Product coverage",
            "",
            f"Registered product IDs ({len(product_ids)}): {_codes(product_ids)}.",
            "",
            "## Workflow-domain coverage",
            "",
            "| Domain | Products | Directory | ID prefixes |",
            "|---|---|---|---|",
        ]
    )
    for row in workflow_domain_rows():
        lines.append(
            f"| `{row['id']}` | {_codes(row['product_ids'])} | `{row['workflow_directory']}` | "
            f"{_codes(row['workflow_prefixes'])} |"
        )

    lines.extend(
        [
            "",
            "## Workflow-pack implementation backlog",
            "",
            f"Registry relationship: `{registry['pack_inventory']['counting_relationship']}`.",
            "",
            "| Pack | Declared | Built | Missing |",
            "|---|---:|---:|---:|",
        ]
    )
    for pack_path in sorted(PACKS_DIR.glob("*.json")):
        source = pack_path.relative_to(ROOT).as_posix()
        rows = [item for item in declarations if item.source == source]
        pack = load_json(pack_path)
        built_count = sum(item.built for item in rows)
        lines.append(
            f"| `{pack.get('pack', pack_path.stem)}` | {len(rows)} | {built_count} | {len(rows) - built_count} |"
        )

    lines.extend(
        [
            "",
            "## Safety status",
            "",
            "All registered catalogs remain `SOURCE_ONLY`; all workflow designs remain `DESIGN_ONLY` and inactive. This inventory does not authorize deployment, credentials, external delivery, provider access, or production activation.",
        ]
    )
    return "\n".join(lines) + "\n"


def main() -> int:
    print(inventory_markdown(), end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
