#!/usr/bin/env python3
"""Inventory declared and built n8n workflows for the N0 completeness gate."""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
PACKS_DIR = ROOT / "automations" / "packs"
WORKFLOWS_DIR = ROOT / "workflows"
CATALOG_FILES = [
    ROOT / "automations" / "catalog.json",
    ROOT / "automations" / "catalog.v2.json",
    ROOT / "automations" / "beyvra.catalog.v2.json",
    ROOT / "automations" / "trading.catalog.v1.json",
]


@dataclass(frozen=True)
class WorkflowDeclaration:
    source: str
    system: str
    workflow_id: str
    expected_path: Path

    @property
    def built(self) -> bool:
        return self.expected_path.is_file()

    @property
    def relative_path(self) -> str:
        return self.expected_path.relative_to(ROOT).as_posix()


def load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def system_from_workflow_id(workflow_id: str) -> str:
    prefix = workflow_id.split(".", 1)[0]
    return {
        "contactcenter": "contact-center",
        "odoo": "contact-center",
        "codestra": "core",
        "postly": "social",
        "larim": "larim-a",
    }.get(prefix, prefix)


def expected_workflow_path(workflow_id: str) -> Path:
    return WORKFLOWS_DIR / system_from_workflow_id(workflow_id) / f"{workflow_id}.json"


def pack_declarations() -> list[WorkflowDeclaration]:
    declarations: list[WorkflowDeclaration] = []
    for pack_path in sorted(PACKS_DIR.glob("*.json")):
        pack = load_json(pack_path)
        for workflow_id in pack.get("workflows", []):
            if not isinstance(workflow_id, str):
                continue
            declarations.append(
                WorkflowDeclaration(
                    source=pack_path.relative_to(ROOT).as_posix(),
                    system=system_from_workflow_id(workflow_id),
                    workflow_id=workflow_id,
                    expected_path=expected_workflow_path(workflow_id),
                )
            )
    return declarations


def catalog_schema_rows() -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for catalog_path in CATALOG_FILES:
        document = load_json(catalog_path)
        workflow_ids: list[str] = []
        if isinstance(document.get("automations"), list):
            workflow_ids = [
                row["id"]
                for row in document["automations"]
                if isinstance(row, dict) and isinstance(row.get("id"), str)
            ]
        elif isinstance(document.get("workflows"), list):
            workflow_ids = [
                row["id"] if isinstance(row, dict) else row
                for row in document["workflows"]
                if isinstance(row, str) or (isinstance(row, dict) and isinstance(row.get("id"), str))
            ]
        rows.append(
            {
                "path": catalog_path.relative_to(ROOT).as_posix(),
                "schema_version": str(document.get("schema_version", "UNDECLARED")),
                "workflow_count": len(workflow_ids),
                "reconciliation_status": (
                    "canonical automation catalog"
                    if catalog_path.name == "catalog.v2.json"
                    else "legacy compatibility catalog"
                    if catalog_path.name == "catalog.json"
                    else "product-specific v2 catalog"
                    if catalog_path.name == "beyvra.catalog.v2.json"
                    else "product-specific legacy catalog pending N5 reconciliation"
                ),
            }
        )
    return rows


def executable_workflow_files() -> list[Path]:
    return sorted(
        path
        for path in WORKFLOWS_DIR.rglob("*.json")
        if "_templates" not in path.parts
    )


def inventory_markdown() -> str:
    declarations = pack_declarations()
    built = sum(1 for item in declarations if item.built)
    lines = [
        "# Workflow Inventory",
        "",
        "Generated by `scripts/workflow_inventory.py` for the N0 declared-equals-present gate.",
        "",
        f"- Pack workflows declared: {len(declarations)}",
        f"- Pack workflows built: {built}",
        f"- Active workflows: 0",
        f"- External effects enabled: false",
        f"- Production changed: false",
        "",
        "## Packs",
        "",
        "| Pack | Declared | Built | Missing |",
        "|---|---:|---:|---:|",
    ]
    for pack_path in sorted(PACKS_DIR.glob("*.json")):
        source = pack_path.relative_to(ROOT).as_posix()
        rows = [row for row in declarations if row.source == source]
        pack = load_json(pack_path)
        lines.append(
            f"| `{pack.get('pack', pack_path.stem)}` | {len(rows)} | "
            f"{sum(1 for row in rows if row.built)} | {sum(1 for row in rows if not row.built)} |"
        )
    lines.extend(["", "## Workflow Status", "", "| Source | Workflow | Expected file | Status |", "|---|---|---|---|"])
    for item in declarations:
        status = "built" if item.built else "missing"
        lines.append(f"| `{item.source}` | `{item.workflow_id}` | `{item.relative_path}` | {status} |")
    lines.extend(["", "## Catalog Schema Reconciliation", "", "| Catalog | Schema | Workflows | N0 reconciliation note |", "|---|---|---:|---|"])
    for row in catalog_schema_rows():
        lines.append(
            f"| `{row['path']}` | `{row['schema_version']}` | {row['workflow_count']} | "
            f"{row['reconciliation_status']} |"
        )
    return "\n".join(lines) + "\n"


def main() -> int:
    print(inventory_markdown(), end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
