#!/usr/bin/env python3
"""Inventory catalog designs and declared/built n8n workflow packs."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

try:
    from .catalog_reconciliation import (
        PACKS_DIR,
        ROOT,
        WORKFLOWS_DIR,
        catalog_reconciliation_snapshot,
        load_json,
        product_rows,
        registry_document,
        workflow_directory_for_id,
        workflow_domain_rows,
    )
except ImportError:
    from catalog_reconciliation import (  # type: ignore
        PACKS_DIR,
        ROOT,
        WORKFLOWS_DIR,
        catalog_reconciliation_snapshot,
        load_json,
        product_rows,
        registry_document,
        workflow_directory_for_id,
        workflow_domain_rows,
    )


@dataclass(frozen=True)
class WorkflowDeclaration:
    source: str
    system: str
    workflow_id: str
    expected_path: Path

    @property
    def built(self) -> bool:
        return self.expected_path.is_file()

    @property
    def relative_path(self) -> str:
        return self.expected_path.relative_to(ROOT).as_posix()


def system_from_workflow_id(workflow_id: str) -> str:
    return workflow_directory_for_id(workflow_id).name


def expected_workflow_path(workflow_id: str) -> Path:
    return workflow_directory_for_id(workflow_id) / f"{workflow_id}.json"


def pack_declarations() -> list[WorkflowDeclaration]:
    declarations: list[WorkflowDeclaration] = []
    for pack_path in sorted(PACKS_DIR.glob("*.json")):
        pack = load_json(pack_path)
        for workflow_id in pack.get("workflows", []):
            if not isinstance(workflow_id, str):
                continue
            expected_path = expected_workflow_path(workflow_id)
            declarations.append(
                WorkflowDeclaration(
                    source=pack_path.relative_to(ROOT).as_posix(),
                    system=expected_path.parent.name,
                    workflow_id=workflow_id,
                    expected_path=expected_path,
                )
            )
    return declarations


def catalog_schema_rows() -> list[dict[str, Any]]:
    return list(catalog_reconciliation_snapshot()["catalog_rows"])


def executable_workflow_files() -> list[Path]:
    return sorted(
        path
        for path in WORKFLOWS_DIR.rglob("*.json")
        if "_templates" not in path.parts
    )


def _join_code(values: list[str]) -> str:
    return ", ".join(f"`{value}`" for value in values)


def inventory_markdown() -> str:
    declarations = pack_declarations()
    built = sum(1 for item in declarations if item.built)
    snapshot = catalog_reconciliation_snapshot()
    registry = registry_document()
    lines = [
        "# Workflow Inventory",
        "",
        "Generated by `scripts/workflow_inventory.py` from the catalog registry and workflow-pack declarations.",
        "",
        "## Authoritative count model",
        "",
        f"- Registered products: {snapshot['registered_products']}",
        f"- Registered workflow domains: {snapshot['registered_workflow_domains']}",
        f"- Registered catalog files: {snapshot['registered_catalogs']}",
        f"- Raw rows across registered catalogs: {snapshot['raw_catalog_entries']}",
        f"- Canonical catalog designs: {snapshot['canonical_designs']}",
        f"- Supplemental unique designs: {snapshot['supplemental_unique_designs']}",
        f"- Compatibility-view rows: {snapshot['compatibility_view_entries']}",
        f"- Deduplicated intended workflow designs: {snapshot['deduplicated_intended_designs']}",
        f"- Pack workflows declared: {len(declarations)}",
        f"- Pack workflows built: {built}",
        f"- Active workflows: {snapshot['active_workflows']}",
        "- External effects enabled: false",
        "- Production changed: false",
        "",
        "> Catalog row counts are not additive. The deduplicated design count includes the canonical catalog plus unique supplemental IDs. Compatibility views contribute zero new designs after alias resolution. Pack declarations are a separate implementation backlog and must never be added to the design count.",
        "",
        "## Catalog reconciliation",
        "",
        "| Catalog | Role | Schema | Rows | Exact canonical overlap | Compatibility aliases | Unique contribution |",
        "|---|---|---:|---:|---:|---:|---:|",
    ]
    for row in snapshot["catalog_rows"]:
        lines.append(
            f"| `{row['path']}` | `{row['role']}` | `{row['schema_version']}` | "
            f"{row['workflow_count']} | {row['exact_canonical_overlap']} | "
            f"{row['alias_count']} | {row['unique_contribution']} |"
        )

    alias_rows = snapshot["alias_rows"]
    lines.extend(
        [
            "",
            "### Compatibility aliases",
            "",
            "| Compatibility catalog | Legacy workflow ID | Canonical workflow ID |",
            "|---|---|---|",
        ]
    )
    if alias_rows:
        for row in alias_rows:
            lines.append(
                f"| `{row['catalog_id']}` | `{row['source']}` | `{row['target']}` |"
            )
    else:
        lines.append("| — | — | — |")

    lines.extend(
        [
            "",
            "## Product registry coverage",
            "",
            "| Product | Display name | Namespace | Domains | Status |",
            "|---|---|---|---|---|",
        ]
    )
    for row in product_rows():
        domains = row.get("domains", [])
        lines.append(
            f"| `{row.get('id')}` | {row.get('display_name')} | `{row.get('namespace')}` | "
            f"{_join_code(domains if isinstance(domains, list) else [])} | `{row.get('status')}` |"
        )

    lines.extend(
        [
            "",
            "## Workflow-domain coverage",
            "",
            "| Domain | Products | Workflow directory | ID prefixes | Design sources |",
            "|---|---|---|---|---|",
        ]
    )
    for row in workflow_domain_rows():
        products = row.get("product_ids", [])
        prefixes = row.get("workflow_prefixes", [])
        design_paths = row.get("design_paths", [])
        design_text = _join_code(design_paths) if design_paths else "—"
        lines.append(
            f"| `{row.get('id')}` | {_join_code(products)} | `{row.get('workflow_directory')}` | "
            f"{_join_code(prefixes)} | {design_text} |"
        )

    lines.extend(
        [
            "",
            "## Workflow-pack implementation backlog",
            "",
            f"Registry relationship: `{registry.get('pack_inventory', {}).get('counting_relationship')}`.",
            "",
            "| Pack | Declared | Built | Missing |",
            "|---|---:|---:|---:|",
        ]
    )
    for pack_path in sorted(PACKS_DIR.glob("*.json")):
        source = pack_path.relative_to(ROOT).as_posix()
        rows = [row for row in declarations if row.source == source]
        pack = load_json(pack_path)
        lines.append(
            f"| `{pack.get('pack', pack_path.stem)}` | {len(rows)} | "
            f"{sum(1 for row in rows if row.built)} | {sum(1 for row in rows if not row.built)} |"
        )

    lines.extend(
        [
            "",
            "## Pack workflow status",
            "",
            "| Source | Workflow | Expected file | Status |",
            "|---|---|---|---|",
        ]
    )
    for item in declarations:
        status = "built" if item.built else "missing"
        lines.append(
            f"| `{item.source}` | `{item.workflow_id}` | `{item.relative_path}` | {status} |"
        )
    return "\n".join(lines) + "\n"


def main() -> int:
    print(inventory_markdown(), end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
